# Generated by Django 5.1.1 on 2024-10-03 19:06

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=tasks.models.get_due_date),
        ),
    ]
